### ISSUE TITLE
No longer working for me - but found workaround

### ISSUE THREAD

**Issue by jacobcritch** [Pauloo27/tiktok-live#10] opened 2022-12-06 03:24 UTC
Tried this on a Live tonight but didn't work - the 'liveUrl' attribute was blank.
I did manage to modify the code to get something working though.

I took a look at the Network tab for the web page
<img width="647" alt="image" src="https://user-images.githubusercontent.com/44329121/205805138-b5ce4e7c-4b14-44bb-81f7-8fb4af531965.png">

Found this 'stream' link. This is the equivalent to the m3u8, it's a .flv I believe.

I hardcoded that into into the script so ffmpeg would copy from there instead.
Maybe we can scrape this stream link somehow without using the API. Unless there is a proper way to do it via API, or if i'm dumb and it still works for other people.

**Comment by ladamrkvicka** [comment] 2023-01-03 23:38
Hi, 

Could you please share your code? I am very interested in trying it but i can't put it together myself. Thank you very much.

**Comment by Pauloo27** [comment] 2023-01-08 19:46
Duplicate of  #11?

**Closed by Pauloo27** 2023-01-08 19:46 UTC
